spring:
  application:
    name: DataParser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_13
    username: nhn_academy_13
    password: EOcV(baaATcu3lny

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect

